### PR TITLE
Add cron to indexer

### PR DESCRIPTION
**Pull request by ptarjan**
We use `cron` to continuously reindex and I imagine other users will want this too

### CODE REVIEW

**Comment by nelhage** [comment]
Hm. Is it hard for `you` to build your own image that does `FROM livegrep/indexer:…` and then installs `cron`? I'm not completely opposed to this, but that seems like the more usual solution to something like this.

**Comment by ptarjan** [comment]
Nope! I totally can do it (and am doing this until it lands) but I thought others might want a cron too so was trying to upstream.

**Comment by alexeagle** [comment]
+1 for adding cron, for a lot of users adding a Dockerfile adds their own layer of build&release complexity. (e.g. it's non-hermetic so under Bazel we discourage users from dynamically building docker images, I'm a maintainer of bazelbuild/rules_docker and would really like to see this land)

**Comment by nelhage** [comment]
Alright, there's no strong reason _not_ to add it on my end, so with two votes I'm happy for it to land!

**Pull request merged**
